name: Deploy to Elastic Beanstalk
on:
  push:
    branches:
      - main

env:
  AWS_APP_NAME: resume-app
  AWS_ENV_NAME: resume-app-env

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip application
        run: |
          cd resume
          zip -r ../application.zip .
          cd ..

      - name: Upload to S3
        run: |
          aws s3 cp application.zip s3://${{ secrets.EB_BUCKET_NAME }}/application-${{ github.run_number }}.zip

      - name: Create app version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "${{ env.AWS_APP_NAME }}" \
            --version-label "v-${{ github.run_number }}" \
            --source-bundle S3Bucket="${{ secrets.EB_BUCKET_NAME }}",S3Key="application-${{ github.run_number }}.zip"

      - name: Deploy
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "${{ env.AWS_ENV_NAME }}" \
            --version-label "v-${{ github.run_number }}"